### ISSUE TITLE
[rush] build command failing with rollup.js

### ISSUE THREAD

**Issue by timini** [microsoft/rushstack#1693]
**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**
i have a package "component-library" in my rush repo which is using rollup for build. When i run the build command i get this error

[!] Error: Cannot find module 'rollup-plugin-typescript'
Require stack:
- /Users/timothy.richardson/go/src/phoenix/monorepo/packages/component-library/rollup.config.js
- /Users/timothy.richardson/go/src/phoenix/monorepo/common/temp/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-plugin-typescript'
Require stack:
- /Users/timothy.richardson/go/src/phoenix/monorepo/packages/component-library/rollup.config.js
- /Users/timothy.richardson/go/src/phoenix/monorepo/common/temp/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/timothy.richardson/go/src/phoenix/monorepo/packages/component-library/rollup.config.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.require.extensions.<computed> [as .js] (/Users/timothy.richardson/go/src/phoenix/monorepo/common/temp/node_modules/rollup/dist/bin/rollup:831:24)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aiml/component-library@0.0.1 build:components: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @aiml/component-library@0.0.1 build:components script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
the rushroot/packages/component-library/node_modules/.bin dir in the package is symlinked to rushroot/common/temp/node_modules/.bin

rollup-plugin-typescript is intalled in rushroot/common/temp/node_modules

* **Tool:RUSH** 
* **Tool Version:5.18.0** 
* **Node Version:v12.13.0** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:OSX**

**Comment by Jabher** [comment]
I can advice you either manually add rollup-plugin-typescript via pnpm hook, or require() it inside rollup config itself, it will probably work
