### ISSUE TITLE
[Heft] Bug: ENOENT error when running via ```pnpm run build -- --watch```

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/rushstack#2077]
**Is this a feature or a bug?**
- [X ] Bug

**Please describe the actual behavior.**

### Summary:  
running ```--watch``` via additional arg to the package.json build script errors.

### Details:

Running the basic ```my-app``` tutorial, up through here:  https://rushstack.io/pages/heft_tutorials/everyday_commands/

** running ```./node_modules/.bin/heft build --watch``` works fine. **

but when I try to run via ```package.json``` build scripts, the seemingly same logic ends in error.

```json
//Package.JSON
   "scripts": {
      "build": "heft test --clean"
   },
```

```bash
# bash
pnpm run build -- --watch

# ends with error: 
Error: ENOENT: no such file or directory, open '/repos/wip-git/rush-test/my-app/.heft/build-cache/jest-cache/haste-map-0a4e394fc89885797375a8c23d266c26-59ef832be3d3cec01b3d07a9a00d4874-8e464c410b92e7e34cd73f6c47484b33'
 ERROR  Command failed with exit code 1.

```

The full output 
```
> my-app@1.0.0 build /repos/wip-git/rush-test/my-app
> heft test --clean "--watch"

Project build folder is "/repos/wip-git/rush-test/my-app"
Starting test
 ---- Clean started ----
Deleted 4 paths
 ---- Clean finished (2ms) ----
 ---- Compile started ----
 ---- Bundle started ----
[copy-static-assets] Copied 0 static assets in 0ms
 ---- Bundle finished (0ms) ----
-------------------- Finished (0.943s) --------------------
Project: my-app@1.0.0
Heft version: 0.4.3
Node version: v14.7.0
Error: ENOENT: no such file or directory, open '/repos/wip-git/rush-test/my-app/.heft/build-cache/jest-cache/haste-map-0a4e394fc89885797375a8c23d266c26-59ef832be3d3cec01b3d07a9a00d4874-8e464c410b92e7e34cd73f6c47484b33'
 ERROR  Command failed with exit code 1.

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at SubprocessTerminalProvider.write (/repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/heft@0.4.3/node_modules/@rushstack/heft/lib/utilities/subprocess/SubprocessTerminalProvider.js:24:17)
    at PrefixProxyTerminalProvider.write (/repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/heft@0.4.3/node_modules/@rushstack/heft/lib/utilities/PrefixProxyTerminalProvider.js:22:22)
    at /repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/node-core-library@3.26.1/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:123:22
    at Set.forEach (<anonymous>)
    at Terminal._writeSegmentsToProviders (/repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/node-core-library@3.26.1/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:102:25)
    at Terminal.write (/repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/node-core-library@3.26.1/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:35:14)
    at Terminal.writeLine (/repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/node-core-library@3.26.1/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:41:46)
    at TypeScriptBuilder.invokeAsync (/repos/wip-git/rush-test/my-app/node_modules/.pnpm/@rushstack/heft@0.4.3/node_modules/@rushstack/heft/lib/plugins/TypeScriptPlugin/TypeScriptBuilder.js:137:34)
Emitted 'error' event on process instance at:
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
^C^C
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Code is identical to the basic ```Heft``` tutorial.   tutorial works, but this seemingly same command does not.

**What is the expected behavior?**
runs same as ```./node_modules/.bin/heft build --watch```

**If this is a bug, please provide the tool version, Node.js version, and OS.**
- node: 14.7.0  ***not lts, have not tested on lts***
- OS:  Ubuntu 20.04 via WSL2 via Win10.
- heft: ^0.4.3
- typescript: 3.9.7  and 4.0beta (tried both)

**Comment by jasonswearingen** [comment]
sorry I am stupid.  my build script isn't build, it's test, and ```--clean``` seems to be the culprit.  I'll open a new bug.
