### ISSUE TITLE
[Heft] ```Heft test --clean --watch``` fails

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/rushstack#2078]
**Is this a feature or a bug?**
- [X ] Bug

**Please describe the actual behavior.**

running ```heft test``` with both ```--clean``` and ```--watch``` options fails with error.

```./node_modules/.bin/heft test --clean --watch```

output:
```bash
Project build folder is "/repos/wip-git/rush-test/xlib"
Starting test
 ---- Clean started ---- 
Deleted 2 paths
 ---- Clean finished (4ms) ---- 
 ---- Compile started ---- 
 ---- Bundle started ---- 
[copy-static-assets] Copied 0 static assets in 1ms
 ---- Bundle finished (1ms) ---- 
-------------------- Finished (0.761s) --------------------
Project: xlib@0.0.1
Heft version: 0.4.2
Node version: v14.7.0
Error: ENOENT: no such file or directory, open '/repos/wip-git/rush-test/xlib/.heft/build-cache/jest-cache/haste-map-a3ce1ec2d8ef991c98a4a2118150e190-2acb2818c066340fe390550d6bc180b4-28d12d61d4a792ff89c29d06d7d1e8a5'

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at SubprocessTerminalProvider.write (/repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/heft@0.4.2/node_modules/@rushstack/heft/lib/utilities/subprocess/SubprocessTerminalProvider.js:24:17)
    at PrefixProxyTerminalProvider.write (/repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/heft@0.4.2/node_modules/@rushstack/heft/lib/utilities/PrefixProxyTerminalProvider.js:22:22)
    at /repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/node-core-library@3.26.0/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:123:22
    at Set.forEach (<anonymous>)
    at Terminal._writeSegmentsToProviders (/repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/node-core-library@3.26.0/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:102:25)
    at Terminal.write (/repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/node-core-library@3.26.0/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:35:14)
    at Terminal.writeLine (/repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/node-core-library@3.26.0/node_modules/@rushstack/node-core-library/lib/Terminal/Terminal.js:41:46)
    at TypeScriptBuilder.invokeAsync (/repos/wip-git/rush-test/xlib/node_modules/.pnpm/@rushstack/heft@0.4.2/node_modules/@rushstack/heft/lib/plugins/TypeScriptPlugin/TypeScriptBuilder.js:80:38)
Emitted 'error' event on process instance at:
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Code used is the basic Heft intro ```my-app`` tutorial. tutorial

**What is the expected behavior?**

runs clean and then watches.  seems that clean is stepping on the build/watch process.

**If this is a bug, please provide the tool version, Node.js version, and OS.**
- node: 14.7.0  ***not lts, have not tested on lts***
- OS:  Ubuntu 20.04 via WSL2 via Win10.
- heft: ^0.4.3
- typescript: 3.9.7  and 4.0beta (tried both)

**Comment by jasonswearingen** [comment]
workaround, create a script like this in ```package.json```
```
 "watch": "heft build --clean ; heft test --watch"
```

**Comment by octogonz** [comment]
This might be a regression from my PR https://github.com/microsoft/rushstack/pull/2064

**Comment by octogonz** [comment]
This is fixed in https://github.com/microsoft/rushstack/pull/2101
