### ISSUE TITLE
[rush] 5.34.0 'rush init' fails with cryptic error message

### ISSUE THREAD

**Issue by chadsowald** [microsoft/rushstack#2207]
**Is this a feature or a bug?**
- [X] Bug

**Please describe the actual behavior.**
```
C:\repo\> rush init
Rush Multi-Project Build Tool 5.34.0 (unmanaged) - https://rushjs.io
Node.js version is 12.18.3 (LTS)

ERROR: The EnvironmentConfiguration must be initialized before values can be accessed.
C:\repo\>
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

All I did was start following this gude: https://rushjs.io/pages/maintainer/setup_new_repo/
```
npm install -g @microsoft/rush   (which succeeded)
rush init                        (which failed as described above)
```

**What is the expected behavior?**
It just works.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool: Rush** 
* **Tool Version: 5.34.0** 
* **Node Version: 12.18.3 (LTS)** 
  * **Is this a LTS version? YES** 
  * **Have you tested on a LTS version? YES** 
* **OS: Win 10**

**Comment by buffcode** [comment]
Same error here when running `rush change` after upgrading to 5.34:

```
$ rush change --verify --target-branch origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_COMMIT_REF_NAME}
/usr/local/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/lib/api/EnvironmentConfiguration.js:127
            throw new Error('The EnvironmentConfiguration must be initialized before values can be accessed.');
            ^
Error: The EnvironmentConfiguration must be initialized before values can be accessed.
    at Function._ensureInitialized (/usr/local/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/lib/api/EnvironmentConfiguration.js:127:19)
    at Function.get rushGlobalFolderOverride [as rushGlobalFolderOverride] (/usr/local/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/lib/api/EnvironmentConfiguration.js:55:34)
    at new RushGlobalFolder (/usr/local/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/lib/api/RushGlobalFolder.js:42:65)
    at new RushVersionSelector (/usr/local/lib/node_modules/@microsoft/rush/lib/RushVersionSelector.js:14:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/rush/lib/start.js:59:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by octogonz** [comment]
This was fixed with https://github.com/microsoft/rushstack/pull/2208 and published as Rush 5.34.1.

Sorry about this regression!  I did test the PR https://github.com/microsoft/rushstack/pull/2188 before releasing, but our normal way of testing Rush builds does not invoke the particular `VersionSelector` code path that reports this error. 🤷‍♂️

**Comment by octogonz** [comment]
@chadsowald and @buffcode thank you for reporting this BTW!

**Comment by buffcode** [comment]
Impressive bug fixing speed ;) Thanks!
