### ISSUE TITLE
[rush] `rush build` failing - issues resolving modules

### ISSUE THREAD

**Issue by katiawheeler** [microsoft/rushstack#2308]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

I am in the process of setting up a monorepo utilizing `rush`. I have a few projects that have a `clean` command that utilizes `rimraf` to clear out the directories before building. When I run `rush build` I receive the following error:

```
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '[redacted]\node_modules\@storybook\core\node_modules\rimraf\bin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  ...2 lines omitted...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ux-utilities@0.4.0 clean: `rimraf build dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ux-utilities@0.4.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     [redacted]\AppData\Roaming\npm-cache\_logs\2020-10-23T15_18_21_632Z-debug.log
```

I have attempted to install `rimraf` globally as well as add it as a dependency to each of the projects that require it. It doesn't seem to help `rush` resolve it correctly. Am I missing something?

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Create a `rush` repo with a few projects that have a `clean` script that utilizes `rimraf`.

**What is the expected behavior?**
`rush` is able to resolve the `rimraf` dependency correctly.

**If this is a bug, please provide the tool version, Node.js version, and OS.**
OS: Windows 10
Node: v12.9.0 (LTS)
Yarn: v1.22.5
Rush: v5.34.4

**Comment by alfonsoar** [comment]
Hi @katiawheeler  - Have you run a `rush update` yet?

I set-up this quick repository to showcase how you can set-up a rush repo with rimraf used in npm scripts. --> https://github.com/alfonsoar/rush-rimraf-demo

**Comment by katiawheeler** [comment]
Hey @alfonsoar,

Yes, I should have posted my steps! I've run `rush update` and `rush install` numerous times with `rush purge` a few times as well to try and get a clean install. The issue seems to be that it wants to resolve `rimraf` from other dependency's `node_modules` folder instead of actually installing the dependency on its own. For example, it looks in `node_modules\@storybook\core\node_modules\rimraf\bin.js` or `node_modules\@jest\core\node_modules\rimraf\bin.js` for `rimraf` instead of at the root `node_modules`.

**Comment by katiawheeler** [comment]
@alfonsoar Also, in your demo, you're using `pnpm` to install your packages - I am using `yarn`.

**Comment by halfnibble** [comment]
Hello @katiawheeler. Could you please put together a small repo that reproduces the error? Thanks.

**Comment by katiawheeler** [comment]
@halfnibble Here's a rough repo setup: https://github.com/katiawheeler/rush-repro

If you clone the repo, run `rush update` and then `rush build`, both packages will fail with an unresolved module for `rimraf`. They both have the same `package.json` as my two failing builds as well, minus some packages hosted on internal npm registry.

OS: Windows 10
Node: v12.9.0 (LTS)
Yarn: v1.19.1
Rush: v5.34.4

Let me know if there's any more info you need!
