### ISSUE TITLE
[heft] Heft invokes API extractor task despite compiler error

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#2478]
## Repro steps

1. Clone the Rush Stack repo.  (I used fc09e5d90b77ae1e818fa2d60a13d497a6d9c015 for this repro)
2. Build the dependencies of `node-core-library`:  
   ```
   $ rush build -T node-core-library
   ``` 
3. Delete the file `libraries/node-core-library/src/TypeUuid.ts`
4. Run `heft --debug build --clean` in that folder

  **Expected result:** 

The TypeScript task should report an error, and API Extractor should not be invoked.

  **Actual result:** 

Both tasks are invoked, producing this error:
```
Encountered 3 errors:
  [typescript] src/AlreadyReportedError.ts:4:26 - (TS2307) Cannot find module './TypeUuid' or its corresponding type declarations.
  [typescript] src/index.ts:89:26 - (TS2307) Cannot find module './TypeUuid' or its corresponding type declarations.
  [typescript] src/test/TypeUuid.test.ts:4:26 - (TS2307) Cannot find module '../TypeUuid' or its corresponding type declarations.
Project: @rushstack/node-core-library@3.36.0
Heft version: 0.23.1
Node version: v14.15.4
Internal Error: getResolvedModule() could not resolve module name "./TypeUuid"
C:/Git/rushstack/libraries/node-core-library/lib/index.d.ts:36:1

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.

Error: Internal Error: getResolvedModule() could not resolve module name "./TypeUuid"
C:/Git/rushstack/libraries/node-core-library/lib/index.d.ts:36:1

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at ExportAnalyzer._fetchSpecifierAstModule (C:\Git\rushstack\common\temp\node_modules\.pnpm\@microsoft\api-extractor@7.12.1\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:583:19)
    at ExportAnalyzer._getExportOfSpecifierAstModule (C:\Git\rushstack\common\temp\node_modules\.pnpm\@microsoft\api-extractor@7.12.1\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:493:41)    
    at ExportAnalyzer._tryMatchExportDeclaration (C:\Git\rushstack\common\temp\node_modules\.pnpm\@microsoft\api-extractor@7.12.1\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:345:29)        
    at ExportAnalyzer.fetchReferencedAstEntity (C:\Git\rushstack\common\temp\node_modules\.pnpm\@microsoft\api-extractor@7.12.1\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:277:45)
    at ExportAnalyzer._tryGetExportOfAstModule (C:\Git\rushstack\common\temp\node_modules\.pnpm\@microsoft\api-extractor@7.12.1\node_modules\@microsoft\api-extractor\lib\analyzer\ExportAnalyzer.js:526:34)
```

## Details

If the compiler task fails with an error, then API Extractor should not be invoked.  The errors it reports may not be meaningful because its input files may not have been built completely.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.23.1 |
| Operating system? |  Windows  |
| Would you consider contributing a PR? | Yes   |
| Node.js version (`node -v`)? | v14.15.4 |

**Comment by iclanton** [comment]
This has been published in Heft 0.24.3.
