### ISSUE TITLE
[rush] pnpm version 6 renamed pnpm binary script to pnmp.cjs from pnpm.js

### ISSUE THREAD

**Issue by matthiasg** [microsoft/rushstack#2681]
pnpm Version 6.2.3

```
Starting "rush audit"

Could not find pnpm at /home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/pnpm-local/node_modules/pnpm/bin/pnpm.js

The script failed with exit code 2

Error: An error occurred.
    at GlobalScriptAction.runAsync (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@microsoft/rush-lib/lib/cli/scriptActions/GlobalScriptAction.js:150:19)
    at GlobalScriptAction.onExecute (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@microsoft/rush-lib/lib/cli/actions/BaseRushAction.js:67:21)
    at GlobalScriptAction.onExecute (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@microsoft/rush-lib/lib/cli/actions/BaseRushAction.js:100:22)
    at GlobalScriptAction._execute (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineAction.js:55:21)
    at RushCommandLineParser.onExecute (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:199:39)
    at RushCommandLineParser._wrapOnExecuteAsync (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@microsoft/rush-lib/lib/cli/RushCommandLineParser.js:141:21)
    at RushCommandLineParser.onExecute (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@microsoft/rush-lib/lib/cli/RushCommandLineParser.js:123:24)
    at RushCommandLineParser.executeWithoutErrorHandling (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:164:25)
    at RushCommandLineParser.execute (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:100:24)
    at Function.launch (/home/gitlab-runner/builds/5sPyHAN7/0/aeppic/aeppic-full/common/temp/install-run/@microsoft+rush@5.45.6/node_modules/@microsoft/rush-lib/lib/api/Rush.js:51:16)
```
## Summary

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | none |
| `rushVersion` from rush.json? |  5.46.1 |
| `useWorkspaces` from rush.json? | NO |
| Operating system? |  Windows / Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14 - 16 |

**Comment by iclanton** [comment]
`rush audit` isn't an OOB Rush command. Can you share your `common/config/command-line.json` entry for `"audit"`?

**Comment by matthiasg** [comment]
Sorry I totally forgot that ! That's it. Though an audit command passthrough to create a license or security audit across all dependencies might be a good improvement for rush too.

**Comment by iclanton** [comment]
That is a good idea. What would you want that to look like? Just the same as running `pnpm audit` in the `common/temp` folder?

**Comment by D4N14L** [comment]
My guess is that instead of building this as a feature for Rush through use of the package manager, we would instead want to implement it by resolving this issue and allowing `pnpm audit` to be run directly with Rush: https://github.com/microsoft/rushstack/issues/2347

**Comment by iclanton** [comment]
Closing this in favor of https://github.com/microsoft/rushstack/issues/2347
