### ISSUE TITLE
[rush] rush version --bump regression causes error between 5.43 and 5.46

### ISSUE THREAD

**Issue by olivierlacan** [microsoft/rushstack#2684]
`rush version --bump` appears to have a regression which occurred somewhere after 5.42.4. The same command works fine in earlier versions.

## Summary

As part of our build process we run: 

```
node common/scripts/install-run-rush.js version --target-branch main --bump
```

This command systematically leads to the following error now: 

```
Another Rush command is already running in this repository.
ERROR: The command failed with exit code 1
```

## Repro steps

  **Expected result:** `rush version --bump` bumps the release version

  **Actual result:** `rush version --bump` exits 1 claiming another rush command is already running when it's not (visibly) the case. 

## Details

Here's the full trace of the error which happens both locally and on a GitLab CI runner running Alpine. I've removed some details with `...` here and there and renamed the app for privacy: 

```
$ node common/scripts/install-run-rush.js version --target-branch main --bump
The rush.json configuration requests Rush version 5.45.5

Invoking "rush version --target-branch main --bump"
---------------------------------------------------



Rush Multi-Project Build Tool 5.45.5 - https://rushjs.io
Node.js version is 14.15.0 (LTS)


Starting "rush version"

Validating package manager shrinkwrap file.

Finding changes in: /app/common/changes

* APPLYING: update for @app/api at 0.2.0
...

* APPLYING: update for @app/content-tools at 0.2.0

* APPLYING: update for @app/player at 0.2.0
...

* APPLYING: Changelog update for "@app/api@0.2.0".

* APPLYING: Changelog update for "@app/content-tools@0.2.0".

* APPLYING: Changelog update for "@app/player@0.2.0".

* DELETING: 33 change file(s).
...

* EXECUTING: /opt/homebrew/bin/git checkout -b version/bump-1620429326337
Branch 'version/bump-1620429326337' set up to track local branch 'main'.
Switched to a new branch 'version/bump-1620429326337'

* EXECUTING: /opt/homebrew/bin/git add . (common/changes)

* EXECUTING: /opt/homebrew/bin/git add :/**/CHANGELOG.json

* EXECUTING: /opt/homebrew/bin/git add :/**/CHANGELOG.md

* EXECUTING: /opt/homebrew/bin/git commit -m Deleting change files and updating change logs for package updates.
The rush.json configuration requests Rush version 5.46.1

Invoking "rush prettier"
------------------------



Rush Multi-Project Build Tool 5.46.1 - https://rushjs.io
Node.js version is 14.15.0 (LTS)


Another Rush command is already running in this repository.

ERROR: The command failed with exit code 1


Error: The command failed with exit code 1

    at Function._processResult (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/utilities/Utilities.js:604:19)
    at Function._executeCommandInternal (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/utilities/Utilities.js:595:19)
    at Function.executeCommand (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/utilities/Utilities.js:219:19)
    at Function.execCommand (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/logic/PublishUtilities.js:153:35)
    at PublishGit.commit (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/logic/PublishGit.js:80:45)
    at VersionAction._gitProcess (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/cli/actions/VersionAction.js:199:24)
    at VersionAction.runAsync (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/cli/actions/VersionAction.js:116:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RushCommandLineParser.onExecute (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:199:13)
    at async RushCommandLineParser._wrapOnExecuteAsync (/app/common/temp/install-run/@microsoft+rush@5.46.1/node_modules/@microsoft/rush-lib/lib/cli/RushCommandLineParser.js:141:9)
```

The following minor versions all seem affected by this regression and there are no documented deprecations or changes between these versions in the changelog that would indicate a behavior difference with `rush version --bump`: 
- 5.46
- 5.45
- 5.44
- 5.43

The only version on which this command runs successfully appears to be 5.42 and below, including the latest patch release 5.42.4.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | (sort of irrelevant since we use `install-run-rush.js` but 5.45.5  |
| `rushVersion` from rush.json? | 5.43 to 5.46 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | macOS, Alpine Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 14.15.0 |

**Comment by iclanton** [comment]
Did you follow [these instructions](https://rushjs.io/pages/maintainer/enabling_prettier/) for setting up Prettier?

Can you confirm that your prettier command in `common/config/command-line.json` includes the `"safeForSimultaneousRushProcesses": true` option?

I don't believe anything was changed in this area any time recently, so I'm not sure what would be causing this. If adding that option doesn't solve the problem, we'll investigate further.

**Comment by olivierlacan** [comment]
> Can you confirm that your prettier command in `common/config/command-line.json` includes the `"safeForSimultaneousRushProcesses": true` option?

It doesn't. Guess we must have missed this change last year: https://github.com/microsoft/rushstack/commit/44ebd9349c4fbb2e3a473310165e6658fe0a77f8

As far as I can tell this fixed the issue.
