### ISSUE TITLE
[rush] Using build with cacheEnabled causes TypeError

### ISSUE THREAD

**Issue by BasKiers** [microsoft/rushstack#2883]
## Summary

We've been trying to upgrade rush from 5.42.2 to 5.52.0.
Since our monorepo is very large we are still in the process of extracting all code to rush packages.
To incrementally refactor the code we have placed all rush packages in a subfolder but kept the legacy code in the root of the repository. We did add the root folder to the `rush.json` file to work the same with `install`/`build` tasks.

After updating, when enabling the local buildCache feature, the `rush build --verbose` shows the following TypeError:
```
Unable to calculate incremental build state: TypeError: Cannot read property 'set' of undefined
Rush will proceed without incremental build, caching, and change detection.
```

```
## Repro steps

I've created a repository to reproduce the issue: https://github.com/BasKiers/rush-example

  **Expected result:** Build caching to work

  **Actual result:** The incremental build setup step throws a TypeError

## Details


By adding logs to the source code of rush-lib I was able to extract the stacktrace. Looking at the code I cannot find a straightforward way of solving this issue (note that due to the changes the linenumbers may vary).
```
TypeError: Cannot read property 'set' of undefined
    at ProjectChangeAnalyzer._getDataAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectChangeAnalyzer.js:217:44)
    at ProjectChangeAnalyzer._tryGetProjectDependenciesAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectChangeAnalyzer.js:80:37)
    at ProjectBuilder._executeTaskAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/taskRunner/ProjectBuilder.js:154:70)
    at ProjectBuilder.executeAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/taskRunner/ProjectBuilder.js:89:31)
    at TaskRunner._executeTaskAndChainAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/taskRunner/TaskRunner.js:197:47)
    at TaskRunner._startAvailableTasksAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/taskRunner/TaskRunner.js:184:36)
    at TaskRunner._executeTaskAndChainAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/taskRunner/TaskRunner.js:230:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async TaskRunner._startAvailableTasksAsync (/home/baskiers/.rush/node-v14.17.3/rush-5.52.0/node_modules/@microsoft/rush-lib/lib/logic/taskRunner/TaskRunner.js:186:9)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | yes |
| `rushVersion` from rush.json? | 5.52.0 |
| `useWorkspaces` from rush.json? |  true |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | v14.17.3 |

**Comment by dmichon-msft** [comment]
Issue was fixed in this commit: https://github.com/microsoft/rushstack/commit/c21927afbc932f26b750ee94c4af013da5719dc6#diff-a97c75b62243d6b88ead5b45905024ed5352dbf21bd23460511267ad924548c6
We just need to publish a new patch version.
