### ISSUE TITLE
[eslint-config] ESLint 8 fails

### ISSUE THREAD

**Issue by clouedoc** [microsoft/rushstack#2998]
## Summary

When using ESLint v8, I get the following error: 

```
Oops! Something went wrong! :(

ESLint: 8.1.0

TypeError: Failed to load plugin '@rushstack/eslint-plugin' declared in '.eslintrc.js » @rushstack/eslint-config/profile/node': Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/clouedoc/Desktop/soundcloud-scraper/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/Users/clouedoc/Desktop/soundcloud-scraper/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/Users/clouedoc/Desktop/soundcloud-scraper/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/clouedoc/Desktop/soundcloud-scraper/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/Users/clouedoc/Desktop/soundcloud-scraper/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

It looks related to https://github.com/eslint/eslint/issues/15149

## Repro steps

```js
// .eslintrc.js
// This is a workaround for https://github.com/eslint/eslint/issues/3458
require('@rushstack/eslint-config/patch/modern-module-resolution');

module.exports = {
  extends: [
    "@rushstack/eslint-config/profile/node",
  ],  // <---- put your profile string here
  parserOptions: { tsconfigRootDir: __dirname }
};
```

In package.json, add eslint v8

## Fix

Edit package.json

```diff
- "eslint": "^8",
+ "eslint": "^7",
```

Then `yarn install`

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-config` version? | ^2.4.4 |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 4.4.4 |
| Node.js version (`node -v`)? | v14.18.0 |

**Comment by chadhietala** [comment]
I have a custom eslint plugin that I'm working on but was interested in using `modern-module-resolution`. I would try something like this as a work around. This seems to have worked for me.

```diff
// .eslintrc.js
// This is a workaround for https://github.com/eslint/eslint/issues/3458
require('@rushstack/eslint-config/patch/modern-module-resolution');

module.exports = {
+ plugins: ['@rushstack/eslint-config'],  
  extends: [
-    "@rushstack/eslint-config/profile/node",
+    "plugin:@rushstack/eslint-config/profile/node",
  ],  // <---- put your profile string here
  parserOptions: { tsconfigRootDir: __dirname }
};
```

**Comment by clouedoc** [comment]
> ```diff
> plugins: ['@rushstack/eslint-config']
> ```

This does not work on my end:

```js
// .eslintrc.js
// This is a workaround for https://github.com/eslint/eslint/issues/3458
require('@rushstack/eslint-config/patch/modern-module-resolution');

module.exports = {
	plugins: ['@rushstack/eslint-config'],
	extends: [
		"plugin:@rushstack/eslint-config/profile/node",
		"plugin:@rushstack/eslint-config/mixins/packlets"
		// "@rushstack/eslint-config/mixins/friendly-locals" // TODO: activate this rule
	],
	parserOptions: { tsconfigRootDir: __dirname }
};
```

```txt
ESLint: 8.2.0

ESLint couldn't find the plugin "@rushstack/eslint-plugin-eslint-config/profile".

(The package "@rushstack/eslint-plugin-eslint-config/profile" was not found when loaded as a Node module from the directory "/Users/clouedoc/Desktop/repositories/tagrecords/mega-repo/no-selenium-supabase".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @rushstack/eslint-plugin-eslint-config/profile@latest --save-dev

The plugin "@rushstack/eslint-plugin-eslint-config/profile" was referenced from the config file in ".eslintrc.js".
```


```jsonc
// package.json
{
  // ...
  "devDependencies": {
    "@rushstack/eslint-config": "^2.4.5",
    "eslint": "^8.2.0",
    "typescript": "^4.2.4"
  },
  // ...
}
```

**Comment by malopgrics** [comment]
Any update ? I have a similar issue to @clouedoc , I had to rollback from eslint `8.8.0` to eslint `7.32.0` for it to work.

**Comment by prescience-data** [comment]
This seems fixed now 🤙🏻
