### ISSUE TITLE
[heft] this._eslintPackage.CLIEngine error while doing heft build command.

### ISSUE THREAD

**Issue by spa5k** [microsoft/rushstack#3093]
## Summary

While running heft build command, the typescript build part works successfully, but the eslint part gives error.

## Repro steps
1. A new rush repo
2. Create a new package
3. Install typescript, eslint, heft as dev deps.
4. update build command to heft build.
5. It gives error.

  **Expected result:** 
Command running successfully.

  **Actual result:** 
```sh
heft --debug build
Searching for a locally installed version of Heft. Use the --unmanaged flag if you want to avoid this
Using local Heft from F:\rush\apps\gaia\node_modules\@rushstack\heft

Project build folder is "F:\rush\apps\gaia"
Starting build
 ---- Pre-compile started ----
 ---- Pre-compile finished (1ms) ----
 ---- Compile started ----
[TypeScript Plugin] Looking for tsconfig at F:/rush/apps/gaia/tsconfig.json
[TypeScript Plugin] Resolved "typescript" as a direct devDependency of the project.
[TypeScript Plugin] Resolved "eslint" as a direct devDependency of the project.
[typescript] Using TypeScript version 4.5.4
[typescript] Configure: 12.051100000739098ms
[typescript] I/O Read: 12.9079000800848ms (97 files)
[typescript] Parse: 359.8238998800516ms (97 files)
[typescript] Program (includes Read + Parse): 459.1662999987602ms
[typescript] Analyze: 180.5426999926567ms
[typescript] Bind: 160.60439997911453ms
[typescript] Check: 7.130300000309944ms
[typescript] Transform: 0ms (0 files)
[typescript] Print: 0.13349999487400055ms (1 files) (Includes Transform)
[typescript] Emit: 0.5516999959945679ms (Includes Print)
[eslint] Using ESLint version 8.4.1
[eslint] The ESLint version is newer than the latest version that was tested with Heft; it may not work correctly:
[eslint] F:\rush\common\temp\node_modules\.pnpm\eslint@8.4.1\node_modules\eslint
[typescript] I/O Write: 0.39740000665187836ms (0 files)
 ---- Compile encountered an error (1499ms) ---- 
-------------------- Finished (1.774s) --------------------
Project: @core/gaia@0.0.1
Heft version: 0.38.2
Node version: v17.2.0
TypeError: this._eslintPackage.CLIEngine is not a constructor

TypeError: this._eslintPackage.CLIEngine is not a constructor
    at Eslint.initializeAsync (F:\rush\common\temp\node_modules\.pnpm\@rushstack+heft@0.38.2\node_modules\@rushstack\heft\lib\plugins\TypeScriptPlugin\Eslint.js:99:27)
    at async Eslint.performLintingAsync (F:\rush\common\temp\node_modules\.pnpm\@rushstack+heft@0.38.2\node_modules\@rushstack\heft\lib\plugins\TypeScriptPlugin\LinterBase.js:40:9)
    at async TypeScriptBuilder._runESlintAsync (F:\rush\common\temp\node_modules\.pnpm\@rushstack+heft@0.38.2\node_modules\@rushstack\heft\lib\plugins\TypeScriptPlugin\TypeScriptBuilder.js:404:9)
    ```
## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.38.2 |
| Operating system? | Windows |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 17.2.0 |

**Comment by iclanton** [comment]
ESLint 8 support was added in Heft `0.43.0`. You need to update your Heft dependency to fix this issue.
