### ISSUE TITLE
[rush] using `watchForChanges` when `rush.json` is not in repoRoot, results in `ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by alber70g** [microsoft/rushstack#3333]
## Summary

I've upgraded my Rush version from `5.56.0` to `5.64.0`
After that, the project assumes `rush.json` being in repo root, which it is not.
In my case, I have `<repoRoot>/app/rush.json` with `<repoRoot>/app/rush/lib/lib-x`

The error I get is: `Error: ENOENT: no such file or directory, watch '/Users/albert/projects/websend/frontend/app/app/rush/tools/eslint-plugin'`
As you can see it includes **`app/app`**, twice `app` instead of once

The full stack trace below

## Repro steps

Create a repo with `rush.json` in a sub-directory

  **Expected result:** run watcher for the files properly

  **Actual result:**  Stack trace
```sh
Error: ENOENT: no such file or directory, watch '/Users/<user>/projects/websend/frontend/app/app/rush/tools/eslint-plugin'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at addWatcher (/Users/<user>/.rush/node-v16.13.1/rush-5.64.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectWatcher.js:116:36)
    at watchedResult (/Users/<user>/.rush/node-v16.13.1/rush-5.64.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectWatcher.js:162:17)
    at new Promise (<anonymous>)
    at ProjectWatcher.waitForChange (/Users/<user>/.rush/node-v16.13.1/rush-5.64.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectWatcher.js:79:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PhasedScriptAction._runWatchPhases (/Users/<user>/.rush/node-v16.13.1/rush-5.64.0/node_modules/@microsoft/rush-lib/lib/cli/scriptActions/PhasedScriptAction.js:194:48)
    at async PhasedScriptAction.runAsync (/Users/<user>/.rush/node-v16.13.1/rush-5.64.0/node_modules/@microsoft/rush-lib/lib/cli/scriptActions/PhasedScriptAction.js:147:13)
    at async RushCommandLineParser.onExecute (/Users/<user>/.rush/node-v16.13.1/rush-5.64.0/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:199:13)
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? |  |
| `rushVersion` from rush.json? |  |
| `useWorkspaces` from rush.json? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by alber70g** [comment]
Fix could be to get the actual `repoRoot` instead of the `rushJsonFolder` here:

https://github.com/microsoft/rushstack/tree/apps/rush-lib/src/logic/ProjectWatcher.ts#L83
