### ISSUE TITLE
[rush] `watchForChanges` fails with `ERROR: Cannot read properties of undefined (reading 'size')` in empty Git repository

### ISSUE THREAD

**Issue by maciejtulaza** [microsoft/rushstack#3686]
## Summary
When I generate new project using `rush init` and create custom command `build:watch` I get error: `ERROR: Cannot read properties of undefined (reading 'size')`

## Repro steps
- Generate new project using `rush init`
- Add two simple modules (both having individual package.json)
    - modules/a
    - modules/b
 - In both modules in package.json add script:
```
"build:watch": "echo 123"
```
- Add these modules to rush.json:
```
{
  "packageName": "a",
  "projectFolder": "modules/a"
},
{
  "packageName": "b",
  "projectFolder": "modules/b"
}
```
- Create custom command in `command-line.json`
```
{
  "name": "build:watch",
  "commandKind": "bulk",
  "summary": "Build projects and watch for changes",
  "incremental": true,
  "enableParallelism": true,
  "watchForChanges": true
}
```
- Try to run `rush --debug build:watch` 

  **Expected result:** 

I expect it to run with watch mode

  **Actual result:** 

I receive an error:
```
ERROR: Cannot read properties of undefined (reading 'size')

TypeError: Cannot read properties of undefined (reading 'size')
    at ProjectWatcher._haveProjectDepsChanged (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectWatcher.js:236:18)
    at ProjectWatcher._computeChanged (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectWatcher.js:214:32)
    at async ProjectWatcher.waitForChange (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/logic/ProjectWatcher.js:64:37)
    at async PhasedScriptAction._runWatchPhases (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/cli/scriptActions/PhasedScriptAction.js:300:48)
    at async PhasedScriptAction.runAsync (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/cli/scriptActions/PhasedScriptAction.js:254:13)
    at async RushCommandLineParser.onExecute (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:211:13)
    at async RushCommandLineParser._wrapOnExecuteAsync (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/cli/RushCommandLineParser.js:199:9)
    at async RushCommandLineParser.onExecute (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/cli/RushCommandLineParser.js:179:13)
    at async RushCommandLineParser.execute (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:101:13)
    at async RushCommandLineParser.execute (/Users/maciejtulaza/.rush/node-v18.10.0/rush-5.81.0/node_modules/@microsoft/rush-lib/lib/cli/RushCommandLineParser.js:153:16)
```
## Details

It seems that the issue happens in this exact line: https://github.com/microsoft/rushstack/blob/3b80e184af2bdd6960e8db47d794f8d6af58c8d6/libraries/rush-lib/src/logic/ProjectWatcher.ts#L290

What I noticed that this is somehow related to `.git` folder. 

I copied all the files I had to an existing .git repo (twice, two different repositories), which I cleaned-out before leaving just `.git` directory and it was all working. Then I removed that `.git` folder and did `git init`. It stopped working.

Looks like it works for existing repos (why?) but not for new ones.

**The issue is there has to be at least one commit in the repo to make it work. Why is that?** I believe rush should be completely independent from Git, but maybe there's something I dont know.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.81.0 |
| `rushVersion` from rush.json? | 5.81.0 |
| `useWorkspaces` from rush.json? | no |
| Operating system? | Mac |
| Would you consider contributing a PR? | probably not |
| Node.js version (`node -v`)? | 18.10.0 |

**Comment by iclanton** [comment]
Rush is actually very coupled to Git. Rush uses Git's fast filesystem analysis for change detection.

@dmichon-msft will take a look at this.
