### ISSUE TITLE
[rush] binaries in node_modules picking up wrong version of other packages 

### ISSUE THREAD

**Issue by beark** [microsoft/rushstack#3729]
## Summary

When you have multiple versions of them in a monorepo, "binaries" (ie, scripts that end up in node_modules/.bin) do not get linked to the appropriate versions of other packages when executed. Instead, they all seem to pick up the same global version of any plugin/addon/dependency they use.

## Repro steps

- Create one package that uses jest, ts-jest, and @types/jest 27.x
- Add some trivial test(s)
- Create one package that uses jest, ts-jest, and @types/jest 29.x
- Add some trivial test(s)
- Try to run tests of each package, note the errors.

  **Expected result:** 

All the tests run and succeed, each with their specific Jest version.

  **Actual result:** 
Something like:
```
 Test suite failed to run

    TypeError: Jest: a transform must export a `process` function.

      at ScriptTransformer._getTransformer (../../common/temp/node_modules/.pnpm/@jest+transform@X.Y.Z/node_modules/@jest/transform/build/ScriptTransformer.js:358:15)
      at ScriptTransformer.transformSource (../../common/temp/node_modules/.pnpm/@jest+transform@X.Y.Z/node_modules/@jest/transform/build/ScriptTransformer.js:420:28)
      at ScriptTransformer._transformAndBuildScript (../../common/temp/node_modules/.pnpm/@jest+transform@X.Y.Z/node_modules/@jest/transform/build/ScriptTransformer.js:524:40)
      at ScriptTransformer.transform (../../common/temp/node_modules/.pnpm/@jest+transform@X.Y.Z/node_modules/@jest/transform/build/ScriptTransformer.js:580:25)
```

## Details

After a bit of debugging, I narrowed this down to the jest "binary" for each package picking up some global ts-jest version, not the version declared in the package.json of each rush package/project.

You can see a live example of this here: https://github.com/beark/propcheck/actions/runs/3381974417/jobs/5616405357. We can also observe that not only is the `ts-jest` version wrong, also the version of `typescript` is not what it should (the package that triggers the warning of an unsupported `typescript` version shouldn't be using 4.8.4, it should be on ~3.9.10).

All of this used to work before I updated rush and pnpm (from 5.62.1 and 6.30.0, respectively). I also switched to `useWorkspaces: true`, which could be related. This all heppened in these two commits:
- https://github.com/beark/propcheck/commit/732ac6ec89a17a33e00b87b00eacaa241c7ece10
- https://github.com/beark/propcheck/commit/3591864aa0b78665bd2d0cb82d8d438fedb8a9bb

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.82.1 |
| `rushVersion` from rush.json? | 5.82.1 |
| `useWorkspaces` from rush.json? | `true` |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 19.0.0 |

**Comment by beark** [comment]
Reverting back to pnpm 6.35.0 and turning off `useWorkspaces` made things work again. When I have some time, I'll experiment a little and see if I can figure out exactly when/what makes things go wrong.

**Comment by iclanton** [comment]
What is the location of the `jest` bin are you executing when you run the command? Is it in the `common/temp/node_modules/bin` folder, or in the project's `node_modules/bin` folder?

@dmichon-msft

**Comment by beark** [comment]
In the project's `node_modules/.bin` folder.

**Comment by beark** [comment]
Locally, I tried pnpm 6.35.0 with `useWorkspaces: true` and got a successful build + test run. But there's still some funkiness with the wrong version of dependencies being linked in. Because two of my compatibility test packages generate warnings:
```
--[ WARNING: compat-jest24 ]--------------------------------[ 13.51 seconds ]--

ts-jest[versions] (WARN) Version 4.8.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.

--[ WARNING: compat-jest25 ]--------------------------------[ 11.70 seconds ]--

ts-jest[versions] (WARN) Version 4.8.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
```
Those projects have a `"typescript": "~3.9.10"` dev dependency, so it's quite surprising that `ts-jest` is run with v4.8.4.
