### ISSUE TITLE
[heft][0.5x] A plugin named "XXX" has already been loaded

### ISSUE THREAD

**Issue by GongT** [microsoft/rushstack#4221]
search tags: "rush" "pnpm" "symlink" "heft.json" "extends"

## Note

This is not a big issue.     
Can easily skip by creating a "toolchain" package.

## Summary

I want to create a rig package, with two profile: `compile` / `compile-and-bundle`.

The `compile-and-bundle` extends `compile`, add more tasks.

I need some custom heft task during two process, so I create plugin in this rig package.

heft can not load my plugins correctly.

## Repro steps

Example Repo: https://github.com/GongT/issues/tree/rushstack-2

1. `pnpm i` // npm did not have this issue, I think
2. `heft --debug --help` 

## Details

I did some debug. I found that `heft` loads same plugin twice from different locations of the symlink. One from realpath, one from node_modules.

I did not found why this only happens when I use `extends` in `heft.json`.

```
Searching for a locally installed version of Heft. Use the "--unmanaged" flag if you want to avoid this.
Config file "[[ROOT]]/config/heft.json" does not exist. Attempting to load via rig.
Error: A plugin named "plugin1" has already been loaded from "[[ROOT]]/example-rig-package/scripts/plugin1.js". Plugins must have unique names.

Error: A plugin named "plugin1" has already been loaded from "[[ROOT]]/example-rig-package/scripts/plugin1.js". Plugins must have unique names.
    at new HeftPluginDefinitionBase ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/configuration/HeftPluginDefinition.js:48:19)
    at new HeftTaskPluginDefinition ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/configuration/HeftPluginDefinition.js:160:1)
    at HeftTaskPluginDefinition.loadFromObject ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/configuration/HeftPluginDefinition.js:165:16)
    at HeftPluginConfiguration._getTaskPluginDefinitions ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/configuration/HeftPluginConfiguration.js:138:97)
    at HeftPluginConfiguration.tryGetTaskPluginDefinitionByName ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/configuration/HeftPluginConfiguration.js:114:70)
    at HeftPluginConfiguration.getPluginDefinitionBySpecifier ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/configuration/HeftPluginConfiguration.js:75:22)
    at HeftTask._loadTaskPluginDefintionAsync ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/pluginFramework/HeftTask.js:85:54)
    at async HeftTask.ensureInitializedAsync ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/pluginFramework/HeftTask.js:69:42)
    at async node_core_library_1.Async.forEachAsync.concurrency ([[ROOT]]/node_modules/.pnpm/@rushstack+heft@0.56.0/node_modules/@rushstack/heft/lib/pluginFramework/InternalHeftSession.js:37:13)
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.56.0 |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 18.12.1 |

**Comment by D4N14L** [comment]
So I did some investigation here. You found a really interesting edge case.

The main issue appears to be caused by your scenario defining plugins within the package containing the Heft configuration you extend from. When this happens, the underlying `Import.resolvePackage` method resolves the path without determining the real path to the package IFF the package name matches the package containing the configuration (since we allow self-referencing). However, the underlying `Import.resolvePackage` method would _not_ use the real-path in this scenario, and would instead return the path containing `.../node_modules/...`. This caused a path mismatch later on, and lead to Heft attempting to load the plugin again, this time with the real-path. This would mean that the same plugin is attempted to be loaded again, but from a different directory.

Fixing the underlying `Import.resolvePackage` method to return the real path eliminates this issue and causes the plugins to load as expected. I'll create a PR to fix this.

Thanks for finding this!
