### ISSUE TITLE
[rush] purge fails with "File does not exist: common/temp/rush-recycler"

### ISSUE THREAD

**Issue by mikeharder** [microsoft/rushstack#4334]
## Summary
Command `rush purge` fails with error `File does not exist: common/temp/rush-recycler`

## Repro steps
```
$ gh repo clone microsoft/rushstack
$ cd rushstack
$ rush install

$ rush --debug purge

Error: File does not exist: /home/mharder/rushstack/common/temp/rush-recycler
ENOENT: no such file or directory, scandir '/home/mharder/rushstack/common/temp/rush-recycler'
    at Object.readdirSync (node:fs:1527:3)
    at /home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@rushstack/node-core-library/lib/FileSystem.js:342:35
    at FileSystem._wrapException (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@rushstack/node-core-library/lib/FileSystem.js:1050:20)
    at FileSystem.readFolderItemNames (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@rushstack/node-core-library/lib/FileSystem.js:340:27)
    at AsyncRecycler.deleteAll (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/dist/commons.js:23910:105)
    at PurgeManager.deleteAll (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/dist/commons.js:14523:39)
    at PurgeAction.runAsync (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/dist/commons.js:8787:22)
    at PurgeAction.onExecute (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/dist/commons.js:6601:21)
    at PurgeAction.onExecute (/home/mharder/.nvm/versions/node/v18.17.1/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/dist/commons.js:6641:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.106.0 |
| `rushVersion` from rush.json? | 5.106.0 |
| `useWorkspaces` from rush.json? | false |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 18.17.1 |

**Comment by iclanton** [comment]
Thanks for reporting this! This has been fixed in Rush `5.108.0`.
