### ISSUE TITLE
[@rushstack/eslint-patch] v1.5.0 -  The "id" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by aravind25dec** [microsoft/rushstack#4368]
Post upgrade of v1.5.0 we are getting the below error in our project, it was working with 1.3.3
Oops! Something went wrong! :(

ESLint: 7.11.0

TypeError [ERR_INVALID_ARG_TYPE]: Cannot read config file: C:\Sites\xxx\xxxx\xxxx\eslint-config\index.js
Error: The "id" argument must be of type string. Received undefined
Referenced from: C:\Sites\xxxx\xxxx\.eslintrc.js
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Module.require (node:internal/modules/cjs/loader:1091:3)
    at require (C:\Sites\xxx\xxx\xxx\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Sites\xxx\xxxx\xxxx\node_modules\@rushstack\eslint-patch\lib\_patch-base.js:180:55)
    at Module._compile (C:\Sites\xxxxx\Web.Ui\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)

**Comment by octogonz** [comment]
Could you test v1.4.0?  It would be super helpful to identify which PR introduced this regression.

**Comment by octogonz** [comment]
@D4N14L could this be a regression from https://github.com/microsoft/rushstack/pull/4353?

**Comment by aravind25dec** [comment]
@octogonz , its perfect v1.4.0 works so good, and I get the expected warnings. I hope the issue is with latest version

✖ 339 problems (0 errors, 339 warnings)


> xxxxxxxx@0.2.1 lint:stylelint
> stylelint "**/*.{css,scss,sass}" --allow-empty-input --config .stylelintrc.js


> xxxxxxxxx@0.2.1 lint:ts
> tsc --noEmit --project .

**Comment by octogonz** [comment]
@D4N14L is fixing it in https://github.com/microsoft/rushstack/pull/4374

**Comment by aravind25dec** [comment]
Hi @octogonz, will there be a new version launching with this fix?

**Comment by octogonz** [comment]
Yes, it automatically publishes on weekdays, but if you need it sooner we can trigger a release manually today

**Comment by aravind25dec** [comment]
If it’s possible please trigger manually and let me know the new version

**Comment by octogonz** [comment]
@aravind25dec it's published now as version 1.5.1 🚀

**Comment by aravind25dec** [comment]
thank you so much @octogonz
