### ISSUE TITLE
[eslint-patch] Error: Failed to patch ESLint because the calling module was not recognized.

### ISSUE THREAD

**Issue by devtobi** [microsoft/rushstack#4764]
## Summary

An error is thrown when trying to use @rushstack/eslint-patch version 1.10.3 together with the version of eslint 8.57.0

## Repro steps

  **Expected result:** 
Successful running of ESLint

  **Actual result:** 
```
 Error: Failed to patch ESLint because the calling module was not recognized.
 If you are using a newer ESLint version that may be unsupported, please create a GitHub issue:
 https://github.com/microsoft/rushstack/issues
     at Object.<anonymous> (/.../node_modules/@rushstack/eslint-patch/lib/_patch-base.js:167:19)
     at Module._compile (node:internal/modules/cjs/loader:1434:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
     at Module.load (node:internal/modules/cjs/loader:1249:32)
     at Module._load (node:internal/modules/cjs/loader:1065:12)
     at Module.require (node:internal/modules/cjs/loader:1271:19)
     at require (node:internal/modules/helpers:123:16)
     at Object.<anonymous> (/.../node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:11:23)
     at Module._compile (node:internal/modules/cjs/loader:1434:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
```

## Details
When I switch back to eslint 8.56.0 everything works fine.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/eslint-plugin-packlets` version? | Not used |
| Operating system? | Mac |
| Would you consider contributing a PR? | Yes |
| TypeScript compiler version? | 5.4.5 |
| Node.js version (`node -v`)? | v22.2.0 ||

**Comment by langehm** [comment]
Same issue when using the following versions:



| Question| Answer|
|------------------------------------------|------------|
| `@rushstack/eslint-plugin-packlets` version? | Not used   |
| Operating system?                        | Cygwin|
| TypeScript compiler version?             | 5.4.5      |
| Node.js version (`node -v`)?             | v20.13.0    |
