### ISSUE TITLE
[rush] 5.126.0+ fails to get git config on `rush install`

### ISSUE THREAD

**Issue by pwbriggs** [microsoft/rushstack#4777]
## Summary

We use a GitHub Actions workflow in our repo to check that the shrinkwrap is in sync with our `package.json` files. The script runs `rush install --check-only`. However, since Rush 5.126.0, the command has been failing, saying

    Unable to determine your Git configuration using this command:

        git config user.email

## Repro steps

👉 Repository available at **[pwbriggs/rush-repro](https://github.com/pwbriggs/rush-repro)**.

1. **`rush init`**
2. **run `rush update` to create scripts** &mdash; *The `common/scripts` directory is not included in `rush init`.*
3. **add a project so `rush install` works properly** &mdash; *`rush install` will complain if there's no dependencies & thus no shrinkwrap.*
4. **add a workflow that uses `rush install`** &mdash; *See the specific workflow I'm using in the repository linked above.*
5. **upgrade `rushVersion` to 5.125.1** &mdash; *✅ This is the last working version.*
6. **upgrade `rushVersion` to 5.126.0** &mdash; ***❌ CI fails on this one for unclear reasons.***

  **Expected result:** `rush install` should work in CI without Git configured.

  **Actual result:**

    Error: Process exited with code 1
    Unable to determine your Git configuration using this command:

        git config user.email

    Error: An error occurred.
        at Git.tryGetGitEmailAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/commons.js:13806:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Module.validateAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/commons.js:23135:21)
        at async Module.validatePolicyAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/commons.js:23255:9)
        at async WorkspaceInstallManager.prepareAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/chunks/InstallManagerFactory.js:486:9)
        at async WorkspaceInstallManager.doInstallAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/chunks/InstallManagerFactory.js:363:83)
        at async WorkspaceInstallManager.doInstallAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/chunks/InstallManagerFactory.js:1355:9)
        at async InstallAction._doInstallAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/commons.js:7328:9)
        at async InstallAction.runAsync (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@microsoft/rush-lib/dist/commons.js:7303:17)
        at async RushCommandLineParser.onExecute (/home/runner/work/rush-repro/rush-repro/common/temp/install-run/@microsoft+rush@5.126.0/node_modules/@rushstack/ts-command-line/lib/providers/CommandLineParser.js:268:13)

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | none; using `install-run-rush.js` in CI |
| `rushVersion` from rush.json? | 5.126.0 |
| `useWorkspaces` from rush.json? | Can't find that in my `rush.json`..? |
| Operating system? | Linux  |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 18.20.3 |

**Comment by kamontat** [comment]
@pwbriggs I created fix on #4772. Waiting for contributors to approve.
