### ISSUE TITLE
[package-deps-hash] git-hash-object is called with all files in a single call, causing failures with message 'The command line is too long.'

### ISSUE THREAD

**Issue by YourGamesBeOver** [microsoft/rushstack#501]
See: 
https://github.com/Microsoft/web-build-tools/blob/5bfc359432db1353f18b0e0c5d9cf85f6700822b/libraries/package-deps-hash/src/getPackageDeps.ts#L86

For packages with more than a few files, this causes 'rush build' to quickly exceed the maximum command line length.  

The call to git-hash-object needs to be either split up among more individual calls with fewer files, or called with --stdin-paths and the files given via stdin

**Comment by nickpape-msft** [comment]
This is definitely an issue. Originally, the code was running this on a per-project basis, but was later changed to hash all the files in the repo simultaneously. This should definitely be fixed. We will probably use the `--stdin-paths` option - that is a good suggestion.

**Comment by pgonzal** [comment]
@YourGamesBeOver do you want to create a PR?

**Comment by sweggersen** [comment]
I got this error today after a large merge with master, for a branch that had been stale for a month and a half:

     Error: git hash-object exited with status null: null
        at getGitHashForFiles (/Users/.../node_modules/@rushstack/package-deps-hash/lib/getPackageDeps.js:87:19)
        at Object.getPackageDeps (/Users/.../node_modules/@rushstack/package-deps-hash/lib/getPackageDeps.js:169:5)

I did some investigation and when I print out the error in `getGitHashForFiles` i get `E2BIG`:

    {
     error: Error: spawnSync /usr/bin/git E2BIG
      at Object.spawnSync (internal/child_process.js:1041:20)
      at Object.spawnSync (child_process.js:616:24)
      at Function.spawnSync (/Users/.../node_modules/@rushstack/package-deps-hash/node_modules/@rushstack/node-core-library/lib/Executable.js:145:30)
      at getGitHashForFiles (/Users/.../node_modules/@rushstack/package-deps-hash/lib/getPackageDeps.js:85:55)
      at Object.getPackageDeps (/Users/.../node_modules/@rushstack/package-deps-hash/lib/getPackageDeps.js:175:5)
      at repl:1:13
      at Script.runInThisContext (vm.js:120:20)
      at REPLServer.defaultEval (repl.js:430:29)
      at bound (domain.js:426:14)
      at REPLServer.runBound [as eval] (domain.js:439:12) {
       errno: 'E2BIG',
       code: 'E2BIG',
       syscall: 'spawnSync /usr/bin/git',
       path: '/usr/bin/git',
       spawnargs: [
        ...{50-100 files}...
        ... 8859 more items
      ]
     },
     status: null,
     signal: null,
     output: null,
     pid: 3031,
     stdout: null,
     stderr: null
    }

Hope this helps!
