### ISSUE TITLE
[rush] ERROR: unacceptable kind of an object to dump (undefined)

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#5053]
## Summary

In [this Zulip thread](https://rushstack.zulipchat.com/#narrow/channel/262513-general/topic/v5.2E147.2E0.20ERROR.3A.20unacceptable.20kind.20of.20an.20object.20to.20dump/near/489816345), Ethan reports an error that appears to be a regression introduced by Rush 5.146.0:

`ERROR: unacceptable kind of an object to dump [object Undefined]`

This is the YAML serializer telling us that it encountered an `undefined` value in one of the objects to be serialized (which is not supported by strict serializers).

I'm guessing it might be this change in [PnpmShrinkWrapFileConverters.ts](https://github.com/microsoft/rushstack/commit/3f9aa731898317547f5b4bc0810a2e82367aa9fb#diff-7fcab69f0e4118d854704a4a23c348ba7dfb9174a66a564a0359d48cbec20da2).   

## Repro steps

***(We haven't isolated a repro yet. I was unable to repro in the Rush Stach repository.)***

  **Expected result:** 

  **Actual result:** 

## Details

`rush --debug update` prints:

```
Running "pnpm install" in /home/devuser/git/align-ts/common/temp


Invoking package manager: /home/devuser/.rush/node-v20.18.0/pnpm-9.13.2/node_modules/pnpm/bin/pnpm.cjs install --store /home/devuser/git/align-ts/common/temp/pnpm-store --config.cacheDir=/home/devuser/git/align-ts/common/temp/pnpm-store --config.stateDir=/home/devuser/git/align-ts/common/temp/pnpm-store --no-prefer-frozen-lockfile --strict-peer-dependencies --config.auto-install-peers=false --config.resolutionMode=highest --config.ignoreCompatibilityDb --recursive --link-workspace-packages false --reporter default

Scope: all 101 workspace projects
../../apps/admin-api-example             |  WARN  deprecated eslint@8.48.0
...onflict-resolution-components-example |  WARN  deprecated @babel/plugin-proposal-private-property-in-object@7.21.11
 WARN  21 deprecated subdependencies found: @babel/plugin-proposal-class-properties@7.18.6, @babel/plugin-proposal-nullish-coalescing-operator@7.18.6, @babel/plugin-proposal-numeric-separator@7.18.6, @babel/plugin-proposal-optional-chaining@7.21.0, @babel/plugin-proposal-private-methods@7.18.6, @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, @types/history@5.0.0, abab@2.0.6, are-we-there-yet@2.0.0, domexception@4.0.0, gauge@3.0.2, glob@7.1.7, glob@7.2.3, glob@8.1.0, inflight@1.0.6, json-schema-ref-parser@9.0.9, npmlog@5.0.1, popper.js@1.16.1, rimraf@3.0.2, stable@0.1.8
.                                        |    +2117 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2098, reused 2015, downloaded 0, added 2117, done
Done in 8.7s


ERROR: unacceptable kind of an object to dump [object Undefined]

YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
    at writeBlockMapping (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
    at writeNode (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
    at writeBlockMapping (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
    at writeNode (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
    at writeBlockMapping (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
    at writeNode (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
    at dump (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
    at Proxy.safeDump (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/js-yaml/lib/js-yaml/dumper.js:823:10)
    at PnpmShrinkwrapFile._serializeInternal (/home/devuser/.nvm/versions/node/v20.18.0/lib/node_modules/@microsoft/rush/node_modules/@microsoft/rush-lib/dist/commons.js:23494:27)
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `rushVersion` from rush.json? |5.147.0  |
| Node.js version (`node -v`)? | 20.15.0 |

**Comment by octogonz** [comment]
Likely a regression from [[rush-lib] Support pnpm lockfile v9 #5009 ](https://github.com/microsoft/rushstack/pull/5009)

@fzxen

**Comment by fzxen** [comment]
@octogonz you are right. The following code caused this issue.
https://github.com/microsoft/rushstack/blob/724aa515c6c2d1a810dc8430576a7994c25ccb37/libraries/rush-lib/src/logic/pnpm/PnpmShrinkWrapFileConverters.ts#L51-L64

After I set the `preventManualShrinkwrapChanges` field in the pnpm-config.json file to true, I successfully reproduced this problem.

I will submit a PR to fix the issue later.

**Comment by lemke-ethan** [comment]
FWIW, here is a repo that you can use to reproduce this error: https://github.com/lemke-ethan/rush-pnpm-unacceptable-kind-of-an-object-to-dump.

**Comment by octogonz** [comment]
🚀 This is fixed in Rush 5.147.2
